# ✅ يخلي Gradle يشتغل بخيوط متعددة (أسرع)
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# ✅ تخصيص RAM للـ JVM (8 جيجا رام + 4 جيجا للـ Metaspace)
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# ✅ إجبار المشروع يستخدم AndroidX
android.useAndroidX=true
android.enableJetifier=true

# ✅ يحسن شوية في الـ R class generation (ممكن يقلل وقت الكومبايل)
android.nonTransitiveRClass=true
