// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8jbu5ypZO__RN9SFvbEOL9ckyTmA6nzs',
    appId: '1:209064067132:android:25412d3d869c7015f80339',
    messagingSenderId: '209064067132',
    projectId: 'saree3-6a6dc',
    storageBucket: 'saree3-6a6dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt4ekTFfY84qi6iDFvFtl2tDIHbaXMPdw',
    appId: '1:209064067132:ios:8f7a0f2e101532cbf80339',
    messagingSenderId: '209064067132',
    projectId: 'saree3-6a6dc',
    storageBucket: 'saree3-6a6dc.firebasestorage.app',
    iosBundleId: 'com.example.saree3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPo4c7AryUuqm_hQV0bZSrSJFelS010zY',
    appId: '1:209064067132:web:d3586520a24c087ff80339',
    messagingSenderId: '209064067132',
    projectId: 'saree3-6a6dc',
    authDomain: 'saree3-6a6dc.firebaseapp.com',
    databaseURL: 'https://saree3-6a6dc-default-rtdb.firebaseio.com',
    storageBucket: 'saree3-6a6dc.firebasestorage.app',
    measurementId: 'G-ZN2P2EF518',
  );

}